ALTER TABLE t_p49767073_dating_app_developme.sessions
  ADD COLUMN IF NOT EXISTS ip VARCHAR(64),
  ADD COLUMN IF NOT EXISTS user_agent TEXT,
  ADD COLUMN IF NOT EXISTS last_active TIMESTAMP DEFAULT NOW();